# Generated by Django 4.1 on 2022-08-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodrecipies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="describtion",
            new_name="description",
        ),
    ]
