# Generated by Django 4.1 on 2022-08-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catagories", "0001_initial"),
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="catagory",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="catagories.catagory",
            ),
        ),
    ]
